service: serverless-demo


provider:
  name: aws
  runtime: python2.7
  profile: sandbox


functions:

  uno:
    handler: router.uno
    events:
      - http:
            path: demo/uno
            method: get
  dos:
    handler: router.dos
    events:
      - http:
            path: demo/dos
            method: get
  tres:
    handler: router.tres
    events:
      - http:
            path: demo/tres
            method: get